import React,{useState} from 'react';
import {Form,Field,Choice,options,Badge,Details,pretty} from './shared';
import {mayReview} from '../workspaceClient';
export default function Activity({page,actions,reviews,registry,overview,session,api,work,busy,setDetail}){
 const [filter,setFilter]=useState(''),[audit,setAudit]=useState([]),[checkpoint,setCheckpoint]=useState('');
 const [agent,setAgent]=useState(''),[task,setTask]=useState(''),[tool,setTool]=useState('database.read'),[resource,setResource]=useState(''),[args,setArgs]=useState('{"limit":3}');
 if(page==='Live Activity')return <section className="panel"><h2>Recent governed actions</h2>{!actions.length?<p>No actions yet. Publish a policy and submit an action in Demo Playground.</p>:<div className="table-scroll"><table><thead><tr><th>Action</th><th>Decision</th><th>State</th><th>Policy</th><th>Inspect</th></tr></thead><tbody>{actions.map(a=><tr key={a.request_id}><td>{a.action.tool||'Invalid action'}<small>{a.request_id.slice(0,12)}</small></td><td><Badge value={a.decision}/></td><td>{a.state}</td><td>{a.policy_version?.slice(0,8)||'None'}</td><td><button className="secondary" onClick={()=>setDetail(a)}>Details</button></td></tr>)}</tbody></table></div>}</section>;
 if(page==='Approvals')return <>{!reviews.length&&<section className="panel"><h2>No pending reviews</h2><p>Requests matching your reviewer groups appear here. Expired requests cannot execute.</p></section>}{reviews.map(a=><section className="panel" key={a.request_id}><div className="row"><h2>{a.action.tool}</h2><Badge value={a.state}/></div><p>Expires {new Date(a.expires_at*1000).toLocaleString()} · Agent {a.agent_id}</p><Details value={a}/><Form title="Review decision" onSubmit={f=>work(()=>api(`/reviews/${a.request_id}/${f.get('decision')}`,{comment:f.get('comment')}),'Review recorded')}><Field label="Reviewer comment" name="comment" maxLength={500}/><Choice label="Decision" name="decision"><option value="approve">Approve exact action</option><option value="reject">Reject</option></Choice><button disabled={busy||!mayReview(a,session?.principal_id)}>Record decision</button>{!mayReview(a,session?.principal_id)&&<p>A separate reviewer must handle an action you initiated.</p>}</Form></section>)}</>;
 if(page==='Audit')return <><Form title="Find audit events" onSubmit={()=>work(async()=>setAudit(await api(`/audit?q=${encodeURIComponent(filter)}`)),'Audit loaded')}><Field label="Search agent, action, decision, policy ID or timestamp" value={filter} onChange={e=>setFilter(e.target.value)}/><button disabled={busy}>Search audit</button></Form><section className="panel"><h2>Integrity and trusted checkpoints</h2><p>Tamper-evident logging. Retain checkpoints outside this server to detect history replacement or tail deletion.</p><div className="row"><button onClick={()=>work(async()=>setDetail(await api('/audit/verify')),'Chain checked')}>Verify chain</button><button onClick={()=>work(async()=>{const c=await api('/audit/checkpoint');setCheckpoint(pretty({organization_id:c.organization_id,event_count:c.event_count,head_hash:c.head_hash}));},'Checkpoint exported; retain an independent copy')}>Export checkpoint</button></div><label>Trusted external checkpoint<textarea value={checkpoint} rows={5} onChange={e=>setCheckpoint(e.target.value)}/></label><button onClick={()=>work(async()=>setDetail(await api('/audit/verify',JSON.parse(checkpoint))),'Checkpoint compared')}>Compare checkpoint</button></section>{audit.map(e=><details className="panel" key={e.sequence}><summary>#{e.sequence} · {e.event_type} · {e.decision||e.state||''} · {e.timestamp}</summary><Details value={e}/></details>)}</>;
 return <><section className="panel"><h2>Real governor decisions on synthetic data</h2><p>Initiate a supported action for a registered agent. Your identity is recorded and cannot approve its own escalation. No agent key is revealed. Delivery is simulated.</p></section><Form title="Propose action" onSubmit={()=>work(async()=>setDetail(await api(`/playground/${agent}`,{task_id:task,tool,resource,arguments:JSON.parse(args)})),'Governor evaluated the action')}><div className="grid"><Choice label="Agent" value={agent} onChange={e=>{setAgent(e.target.value);setTask('');}} required><option value="">Choose registered agent</option>{options(registry.agents.filter(a=>a.state==='ACTIVE'))}</Choice><Choice label="Assigned task" value={task} onChange={e=>setTask(e.target.value)} required><option value="">Choose task</option>{options(registry.tasks.filter(t=>t.data.agents.includes(agent)))}</Choice><Choice label="Supported tool" value={tool} onChange={e=>{setTool(e.target.value);setResource('');setArgs(e.target.value==='database.read'?'{"limit":3}':e.target.value==='report.create'?'{"source_artifact_id":"PASTE_READ_ARTIFACT_ID","format":"csv"}':'{"artifact_id":"PASTE_REPORT_ARTIFACT_ID","recipient":"review@example.test"}');}}><option>database.read</option><option>report.create</option><option>report.send</option></Choice><Choice label="Task resource" value={resource} onChange={e=>setResource(e.target.value)} required><option value="">Choose resource</option>{options(registry.connectors.filter(c=>registry.tasks.find(t=>t.id===task)?.data.resources.includes(c.id)&&overview?.capabilities[c.data.kind]?.includes(tool)))}</Choice></div><label>Strict tool arguments<textarea rows={6} value={args} onChange={e=>setArgs(e.target.value)}/></label><button disabled={busy}>Submit governed action</button></Form></>;
}
