import React,{useState} from 'react';
import {Form,Field,Choice,options,Badge,Details,pretty} from './shared';
import {diffRules,mayPublish} from '../workspaceClient';
export default function Policies({sources,policies,jobs,registry,overview,api,work,can,busy,permissions}){
 const [selected,setSelected]=useState(null),[editor,setEditor]=useState('[]');
 function edit(p){setSelected(p);setEditor(pretty(p.data.rules));}
 async function operation(action){await work(async()=>{const p=await api(`/policies/${selected.id}/${action}`,action==='publish'?{expected_active_policy_id:overview.active_policy_id}:{});edit(p);},`Policy ${action} completed`);}
 let rules=[];try{const parsed=JSON.parse(editor);rules=Array.isArray(parsed)?parsed:[];}catch{/* editor may be incomplete */}
 const source=sources.find(s=>s.id===rules[0]?.source?.source_id)||sources[0];
 const active=policies.find(p=>p.id===overview?.active_policy_id);
 return <><section className="grid">{can('sources')&&<><Form title="Upload company policy" onSubmit={form=>work(async()=>{const s=await api('/sources/upload',form);const all=await api('/policies');edit(all.find(p=>p.id===s.draft_id));},'Source extracted; policy remains a draft')}><Field label="PDF, Markdown or text · maximum 2 MiB" type="file" name="file" accept=".pdf,.md,.txt" required/><Choice label="Revision of an existing source (optional)" name="previous_id"><option value="">New source</option>{options(sources)}</Choice><button disabled={busy}>Upload source</button></Form><Form title="Import approved policy URL" onSubmit={form=>work(()=>api('/sources/url',Object.fromEntries(form)),'URL imported as draft evidence')}><Field label="HTTPS URL on an administrator-allowed host" type="url" name="url" required/><button disabled={busy}>Import URL</button></Form></>}</section><section className="panel"><h2>Policy versions</h2>{policies.length?policies.map(p=><button className="list-item" key={p.id} onClick={()=>edit(p)}><span>{p.name}<small>{p.id.slice(0,8)} · revision {p.data.revision}</small></span><Badge value={p.state}/></button>):<p>Upload a source to begin. No published policy means deny by default.</p>}</section>
 {can('drafts')&&sources.length>0&&<Form title="Propose rules without a cloud model" onSubmit={form=>work(()=>{if(!selected)throw new Error('Select a draft first');const task=registry.tasks.find(t=>t.id===form.get('task'));if(!task)throw new Error('Choose a task');const resources={};for(const c of registry.connectors){const tool=({demo_sales:'database.read',report_storage:'report.create',simulated_delivery:'report.send'})[c.data.kind];if(tool&&task.data.resources.includes(c.id))resources[tool]=c.id;}return api('/compilations',{source_id:form.get('source'),policy_id:selected.id,mode:'manual',configuration:{role:form.get('role'),task_id:task.id,resources,reviewer_group:form.get('group'),destinations:['review@example.test']}});},'Suggestions queued; reload the draft after compilation succeeds')}><div className="grid"><Choice label="Source" name="source">{options(sources)}</Choice><Choice label="Task" name="task" required><option value="">Choose task</option>{options(registry.tasks)}</Choice><Field label="Business role" name="role" defaultValue="data_analyst" required/><Choice label="Reviewer group" name="group">{options(registry.groups)}</Choice></div><button disabled={busy||!selected||selected.state!=='DRAFT'}>Generate draft suggestions</button><p className="muted">Verify every suggestion, then resolve its assumptions in the editor.</p>{jobs.slice(0,3).map(j=><p key={j.id}>{j.id.slice(0,8)} <Badge value={j.state}/>{j.data.error}</p>)}</Form>}
 {selected&&<section className="panel"><div className="row"><h2>{selected.name}</h2><Badge value={selected.state}/><button className="secondary" onClick={()=>edit(policies.find(p=>p.id===selected.id)||selected)}>Reload selected version</button></div><div className="split"><div><h3>Source evidence</h3>{source?<><p>{source.name} · revision {source.data.revision}</p>{source.data.segments.map(s=><blockquote key={s.index}><small>{s.reference}</small><p>{s.text}</p></blockquote>)}</>:<p>Select a source for citations.</p>}</div><div><label>Structured rules<textarea aria-label="Structured rules" rows={25} value={editor} readOnly={!can('drafts')||!['DRAFT','VALIDATED'].includes(selected.state)} onChange={e=>setEditor(e.target.value)}/></label><p className="muted">Explicit role, tool, resource, task, constraints, decision, reviewer group and source citation. No executable expressions.</p></div></div>{selected.data.validation_errors?.length>0&&<ul className="error">{selected.data.validation_errors.map((e,i)=><li key={i}>{e}</li>)}</ul>}<div className="row">{can('drafts')&&<><button disabled={busy||!['DRAFT','VALIDATED'].includes(selected.state)} onClick={()=>work(async()=>edit(await api('/policies',{id:selected.id,name:selected.name,expected_revision:selected.data.revision,rules:JSON.parse(editor)})),'Draft saved')}>Save draft</button><button disabled={busy||selected.state!=='DRAFT'} onClick={()=>operation('validate')}>Validate saved draft</button><button className="secondary" disabled={busy} onClick={()=>operation('clone')}>Clone as new draft</button></>}{can('publish')&&<button disabled={busy||!mayPublish(selected,permissions)||editor!==pretty(selected.data.rules)} onClick={()=>operation('publish')}>Publish validated policy</button>}</div><h3>Diff against active policy</h3>{diffRules(active?.data.rules,rules).map(d=><details key={d.id}><summary>{d.status}: {d.id}</summary><div className="split"><Details value={d.before||'Absent'}/><Details value={d.after||'Absent'}/></div></details>)}</section>}</>;
}

