import React,{useState} from 'react';
import {Form,Field,Choice,options,Badge,Details} from './shared';
export default function Registry({registry,members,api,work,can,busy,setDetail}){
 const [key,setKey]=useState(null);
 return <><section className="grid">{can('connectors')&&<Form title="Connect supported resource" onSubmit={f=>work(()=>api('/connectors',{name:f.get('name'),kind:f.get('kind'),destinations:f.get('kind')==='simulated_delivery'?['review@example.test']:[]}),'Resource registered')}><Field label="Display name" name="name" required/><Choice label="Connector" name="kind"><option value="demo_sales">Demo sales database</option><option value="demo_support">Demo support database</option><option value="report_storage">Protected report artifacts</option><option value="simulated_delivery">Simulated delivery only</option></Choice><button disabled={busy}>Connect resource</button></Form>}{can('agents')&&<Form title="Register agent" onSubmit={f=>work(()=>api('/agents',Object.fromEntries(f)),'Agent registered')}><Field label="Agent name" name="name" required/><Field label="Business role" name="role" defaultValue="data_analyst" pattern="[a-z][a-z0-9_-]{1,49}" required/><button disabled={busy}>Register agent</button></Form>}{can('members')&&<Form title="Create reviewer group" onSubmit={f=>work(()=>api('/groups',Object.fromEntries(f)),'Group created')}><Field label="Group name" name="name" defaultValue="Managers" required/><button disabled={busy}>Create group</button></Form>}</section>
 <section className="grid"><div className="panel"><h2>Registered agents</h2>{registry.agents.length?registry.agents.map(a=><article className="record" key={a.id}><h3>{a.name}</h3><p>{a.data.role} · <Badge value={a.state}/></p><small>{a.id}</small>{can('agents')&&<div className="row"><button disabled={busy||a.state!=='ACTIVE'} onClick={()=>work(async()=>setKey(await api(`/agents/${a.id}/key`,{})),'Key generated; copy it securely now')}>Generate key</button><button className="danger" disabled={busy||a.state!=='ACTIVE'} onClick={()=>work(()=>api(`/agents/${a.id}/revoke`,{}),'Agent and keys revoked')}>Revoke agent</button></div>}</article>):<p>No agents registered yet.</p>}</div><div className="panel"><h2>Resource connections</h2>{registry.connectors.map(c=><article className="record" key={c.id}><h3>{c.name}</h3><p>{c.data.kind==='simulated_delivery'?'Simulated delivery':c.data.kind.startsWith('demo_')?'Demo connector':'Local artifact storage'}</p><small>{c.id}</small>{can('connectors')&&<button className="secondary" onClick={()=>work(async()=>setDetail(await api(`/connectors/${c.id}/test`,{})),'Connection checked')}>Test connection</button>}</article>)}</div></section>
 {key&&<section className="panel secret" role="status"><h2>Copy this agent key now</h2><p>Displayed once and stored only as a hash. Never embed it in frontend code.</p><code>{key.key}</code><button onClick={()=>setKey(null)}>I have saved it securely</button></section>}
 {can('agents')&&<Form title="Create a scoped task" onSubmit={f=>work(()=>api('/tasks',{name:f.get('name'),roles:f.get('roles').split(',').map(s=>s.trim()),resources:f.getAll('resources'),agents:f.getAll('agents')}),'Task and assignments created')}><Field label="Task name" name="name" defaultValue="sales-report" required/><Field label="Permitted business roles, comma separated" name="roles" defaultValue="data_analyst" required/><div className="grid"><Choice label="Resources · Ctrl/Cmd for multiple" name="resources" multiple size={4}>{options(registry.connectors)}</Choice><Choice label="Assigned agents · can assign after publication" name="agents" multiple size={4}>{options(registry.agents)}</Choice></div><button disabled={busy}>Create task</button></Form>}
 <section className="panel"><h2>Task assignments</h2>{registry.tasks.map(t=><article className="record" key={t.id}><h3>{t.name}</h3><p>{t.data.roles.join(', ')} · {t.data.agents.length} agents · {t.data.resources.length} resources</p><small>{t.id}</small>{can('agents')&&<Form title="Update assignments" onSubmit={f=>work(()=>api('/tasks',{id:t.id,name:t.name,...t.data,agents:f.getAll('agents')}),'Assignment updated')}><Choice label="Assigned agents" name="agents" multiple defaultValue={t.data.agents}>{options(registry.agents)}</Choice><button disabled={busy}>Save assignments</button></Form>}</article>)}</section>
 {can('members')&&<Form title="Provision or update membership" onSubmit={f=>work(()=>api('/members',{email:f.get('email'),password:f.get('password')||null,permissions:f.get('permissions').split(',').map(p=>p.trim()).filter(Boolean),groups:f.getAll('groups')}),'Membership updated')}><Field label="Email" type="email" name="email" required/><Field label="Initial password for a new account only" type="password" name="password" minLength={12} autoComplete="new-password"/><Field label="Workspace permissions, comma separated" name="permissions" defaultValue="review,activity,audit"/><Choice label="Reviewer groups" name="groups" multiple>{options(registry.groups)}</Choice><p className="muted">Permissions: members, sources, drafts, publish, agents, connectors, review, audit, activity, playground. Leave password blank for existing accounts.</p><button disabled={busy}>Save membership</button><Details value={members}/>{members.map(m=><button type="button" key={m.id} className="danger" disabled={busy||!m.active} onClick={()=>work(()=>api(`/members/${m.id}/revoke`,{}),'Membership revoked')}>Revoke {m.email}</button>)}</Form>}</>;
}

