from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Decision(str, Enum):
    """
    Final Governor decision.
    """

    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    ESCALATE = "ESCALATE"


class ActionState(str, Enum):
    """
    Lifecycle of an action.

    PROPOSED
        Action has been received but not evaluated yet.

    BLOCKED
        Governor denied the action.

    ALLOWED
        Governor allowed the action.

    PENDING_APPROVAL
        Action requires human approval.

    APPROVED
        Human approved the action.

    REJECTED
        Human rejected the action.

    EXPIRED
        Approval expired before execution/revalidation.

    REVALIDATED
        Approved action was checked again and is still identical
        to the originally approved action.

    REVALIDATION_FAILED
        The action changed after approval or its security context
        is no longer valid.

    EXECUTING
        Action is currently being executed.

    COMPLETED
        Execution completed successfully.

    FAILED
        Execution failed.
    """

    PROPOSED = "PROPOSED"
    BLOCKED = "BLOCKED"
    ALLOWED = "ALLOWED"

    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"

    REVALIDATED = "REVALIDATED"
    REVALIDATION_FAILED = "REVALIDATION_FAILED"

    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ApprovalState(str, Enum):
    """
    Lifecycle of a human approval request.

    PENDING
        Waiting for human decision.

    APPROVED
        Human approved the exact action.

    REJECTED
        Human rejected the action.

    EXPIRED
        Approval request exceeded its TTL.

    REVALIDATED
        Approved action was rechecked and remains unchanged.

    REVALIDATION_FAILED
        Action changed after approval or is no longer valid.
    """

    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"

    REVALIDATED = "REVALIDATED"
    REVALIDATION_FAILED = "REVALIDATION_FAILED"


class ActionRequest(BaseModel):
    """
    Normalized action proposed by an AI agent.

    The source can be:

        text
        image extraction
        voice transcription

    All three ultimately produce the same ActionRequest
    before entering the Governor.
    """

    task_id: str = Field(min_length=1)

    tool: str = Field(min_length=1)

    resource: str = Field(min_length=1)

    arguments: dict[str, Any] = Field(
        default_factory=dict
    )


class TrustedActionContext(BaseModel):
    """
    Backend-controlled security context.

    The agent/client must NOT be allowed to choose:

        role
        provenance
        environment
        approval state

    These values are attached by trusted backend logic.
    """

    agent_id: str = Field(min_length=1)

    role: str = Field(min_length=1)

    task_scope: str = Field(min_length=1)

    provenance: str = Field(
        default="trusted_internal"
    )

    environment: str = Field(
        default="local"
    )


class RiskAssessment(BaseModel):
    """
    Risk result generated by the Governor's risk engine.
    """

    score: int = Field(
        ge=0,
        le=100,
    )

    level: str

    factors: list[str] = Field(
        default_factory=list
    )


class DecisionResponse(BaseModel):
    """
    Result returned by the Governor.

    This object describes what should happen.

    IMPORTANT:
        DecisionResponse does NOT execute the action.

    Execution is performed later by the restricted
    execution layer.
    """

    action_id: str

    decision: Decision

    state: ActionState

    reason: str

    risk: RiskAssessment

    requires_approval: bool = False

    latency_ms: float